name: Cypress Typescript Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run Cypress
      uses: cypress-io/github-action@v6
      with: 
        node-version: 22